In [1]:
# 1  Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
import numpy as np
arr1d = np.array([[[10,30]]])
arr1d
arr1d.ndim

3

In [2]:
#2 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
arr2d = np.arange(34,113,6)
arr2d

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [3]:
#3 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
arr3d = np.linspace(50,500, 91, dtype='int')
arr3d

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [5]:
#4  100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
arr4d = np.logspace(8, -1, 8)
arr4d

array([1.00000000e+08, 5.17947468e+06, 2.68269580e+05, 1.38949549e+04,
       7.19685673e+02, 3.72759372e+01, 1.93069773e+00, 1.00000000e-01])

In [6]:
#5 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
arr5d = np.arange(0,9).reshape(3,3)
arr5d
     

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#6 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
arr6d = np.zeros((6, 6), dtype='int')
arr6d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
#7 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
arr7d = np.ones((4,4), dtype='int')
arr7d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
#8 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
arr8d = np.eye((8), dtype= 'int')
arr8d

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [10]:
#9 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
arr9d = np.eye((5), dtype=int)*3
arr9d

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [11]:
#10 np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.
arr10d = np.random.rand(6)
arr10d

array([0.47333087, 0.98032228, 0.14951722, 0.83203336, 0.24375291,
       0.15225411])

In [12]:
#11 np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

arr11d =np.random.randint(50, 101, (5,2))
arr11d
     

array([[55, 64],
       [80, 53],
       [88, 80],
       [51, 51],
       [74, 83]])

In [13]:
#12 np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.
arr12d = np.random.randint(100,1000,50).reshape(2,5,5)
arr12d
arr12d.ndim
arr12d.dtype

dtype('int64')

In [14]:
#13 np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.
arr13d = np.random.randint(0,101,10)
max13_value = np.max(arr13d)
min13_value = np.min(arr13d)
arr13d
max13_value, min13_value

(100, 3)

In [15]:
#14 np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.
arr14d = np.random.randint(300,501,20).reshape(2,2,5)
arr14d

min_number = arr14d[2:2:1]
min_number


array([], shape=(0, 2, 5), dtype=int64)

In [16]:
#15 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.
arr15d = np.arange(0,51)
arr15d[20:36] = 500
arr15d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])